### ISSUE TITLE
Can't import GPyOpt

### ISSUE THREAD

**Issue by labodyn** [SheffieldML/GPyOpt#114]
>>> import GPyOpt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lander/miniconda3/envs/yazzoom_pipeline/lib/python3.6/site-packages/GPyOpt/__init__.py", line 7, in <module>
    from GPyOpt.core.task.space import Design_space
  File "/home/lander/miniconda3/envs/yazzoom_pipeline/lib/python3.6/site-packages/GPyOpt/core/__init__.py", line 4, in <module>
    from .bo import BO
  File "/home/lander/miniconda3/envs/yazzoom_pipeline/lib/python3.6/site-packages/GPyOpt/core/bo.py", line 7, in <module>
    from ..util.general import best_value, reshape
  File "/home/lander/miniconda3/envs/yazzoom_pipeline/lib/python3.6/site-packages/GPyOpt/util/general.py", line 5, in <module>
    from scipy.special import erfc
  File "/home/lander/miniconda3/envs/yazzoom_pipeline/lib/python3.6/site-packages/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
ImportError: cannot import name 'show_config'

**Comment by labodyn** [comment]
Solved it by installing scipy separately.

**Comment by javiergonzalezh** [comment]
Great that you managed to fix it.

2017-10-06 16:18 GMT+01:00 Lander Bodyn <notifications@github.com>:
