### ISSUE TITLE
Impossible to run "First steps"

### ISSUE THREAD

**Issue by MatthieuBizien** [SheffieldML/GPyOpt#124]
I can't run http://sheffieldml.github.io/GPyOpt/firststeps/index.html on a fresh install. 

The error:
```python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from GPyOpt.methods import BayesianOptimization
>>> import numpy as np
>>> def f(x): return (6*x-2)**2*np.sin(12*x-4)
... 
>>> bounds = [(0,1)]
>>> myBopt = BayesianOptimization(f=f, bounds=bounds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matthieu/Programmes/anaconda3/lib/python3.6/site-packages/GPyOpt/methods/bayesian_optimization.py", line 94, in __init__
    self.space = Design_space(self.domain, self.constrains)
  File "/home/matthieu/Programmes/anaconda3/lib/python3.6/site-packages/GPyOpt/core/task/space.py", line 72, in __init__
    self._translate_space(self.config_space)
  File "/home/matthieu/Programmes/anaconda3/lib/python3.6/site-packages/GPyOpt/core/task/space.py", line 173, in _translate_space
    for i, d in enumerate(space):
TypeError: 'NoneType' object is not iterable
```

Dependencies:
```Python

>>> import numpy as np; np.__version__
'1.13.3'
>>> import scipy as sp; sp.__version__
'0.19.1'
>>> import GPy; GPy.__version__
'1.8.4'
```

I have Ubuntu 16.04

**Comment by javiergonzalezh** [comment]
Hi @MatthieuBizien,

The problem is that we are not supporting anymore passing the bounds as a list, you need to define a dictionary.  So, if you do:

bounds = [{'name': 'var_1', 'type': 'continuous', 'domain': (-1,1)}]

it should work. We have already updated the web to avoid confusion.

Thanks for your interests!
