### ISSUE TITLE
Impossible to run "First steps"

### ISSUE THREAD

**Issue by Yatoom** [SheffieldML/GPyOpt#126]
Someone posted issue [124](https://github.com/SheffieldML/GPyOpt/issues/124), which is now closed. However, the code on the website still results in an error. I am using version  `1.2.0`.

```python
# --- Load GPyOpt
from GPyOpt.methods import BayesianOptimization
import numpy as np

# --- Define your problem
def f(x): return (6*x-2)**2*np.sin(12*x-4)
bounds = [{'name': 'var_1', 'type': 'continuous', 'domain': (0,1)}]

# --- Solve your problem
myBopt = BayesianOptimization(f=f, bounds=bounds)
myBopt.run_optimization(max_iter=15)
myBopt.plot_acquisition()
```

```
Traceback (most recent call last):
  File "/home/jhoof/PycharmProjects/IntegerTransformation/test.py", line 10, in <module>
    myBopt = BayesianOptimization(f=f, bounds=bounds)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/methods/bayesian_optimization.py", line 94, in __init__
    self.space = Design_space(self.domain, self.constrains)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/core/task/space.py", line 72, in __init__
    self._translate_space(self.config_space)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/core/task/space.py", line 173, in _translate_space
    for i, d in enumerate(space):
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1
```

**Comment by apaleyes** [comment]
Hi. It appears we did not fully updated the page while fixing #124 . It is now corrected - please use "space" instead of "bounds" for the parameter name.

**Comment by javiergonzalezh** [comment]
Thanks @apaleyes  for fixing that!

**Comment by Yatoom** [comment]
The new code gives this problem:

```
Traceback (most recent call last):
  File "/home/jhoof/PycharmProjects/IntegerTransformation/test.py", line 10, in <module>
    myBopt = BayesianOptimization(f=f, space=space)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/methods/bayesian_optimization.py", line 94, in __init__
    self.space = Design_space(self.domain, self.constrains)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/core/task/space.py", line 72, in __init__
    self._translate_space(self.config_space)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/core/task/space.py", line 173, in _translate_space
    for i, d in enumerate(space):
TypeError: 'NoneType' object is not iterable
```

The `space` parameter is not passed to the `Design_space` object in the `__init__` function of the `BayesianOptimization` class:
```python
# --- CHOOSE design space
self.constrains = constrains
self.domain = domain
self.space = Design_space(self.domain, self.constrains)
```

**Comment by apaleyes** [comment]
Never, never do fixes in the middle of the night. It ought to be domain, not space and not bounds. Not sure what I was thinking
