### ISSUE TITLE
running with suggested config file doesn't work

### ISSUE THREAD

**Issue by Carldeboer** [SheffieldML/GPyOpt#155]
Hi!  Not sure this is a config problem or not (although running GPyOpt in python appears to work so far.  Directly running the example from the tutorial here (http://sheffieldml.github.io/GPyOpt/firstexamples/index.html) gives me an error:
```
$ gpyopt.py config_ex.json
Traceback (most recent call last):
  File "/home/unix/cgdeboer/.conda/envs/GPyOptEnv/bin/gpyopt.py", line 20, in <module>
    bo = driver.run()
  File "/home/unix/cgdeboer/.conda/envs/GPyOptEnv/lib/python2.7/site-packages/GPyOpt/interface/driver.py", line 105, in run
    space = self._get_space()
  File "/home/unix/cgdeboer/.conda/envs/GPyOptEnv/lib/python2.7/site-packages/GPyOpt/interface/driver.py", line 38, in _get_space
    assert 'space' in self.config, 'The search space is NOT configured!'
AssertionError: The search space is NOT configured!
```

I also note that I can't find much in the way of documentation regarding the syntax of these config files. 

Finally, the link at the bottom of this page (http://sheffieldml.github.io/GPyOpt/tutorial/index.html) 
`Check the GPyOpt documentation for details of the different functionalities.`
is broken.

**Comment by apmcleod** [comment]
Same problem here, and unable to find json file specs. I think the documentation may have moved [here](https://gpyopt.readthedocs.io/en/latest/) (per https://github.com/SheffieldML/GPyOpt/issues/164), but I can't find anything about the config file there.

**Comment by fanhanwei** [comment]
I meet the same problem, the code tutorial seems provide us with a wrong example.
I finally remove the bugs by changing the "variables" part of the json file to the code below：
`    "space" : {
        "x": { "name": "var_1",
            "type" : "continuous",
            "dimensionality" : 1,
            "domain"  : "(-1,1)"
        },
        "y": {"name": "var_2",
            "type" : "continuous",
            "dimensionality" : 1,
            "domain"  : "(-2,2)"
        }
    },`

meanwhile，add the below code into line93 of  GPyOpt.core.task.space.py
`        space = [space['x'], space['y']]`

But it seems like I will always need to change the space.py when changing variables.
