### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by ahundt** [SheffieldML/GPyOpt#163]
```
± pip install gpy gpyopt --user --upgrade
Collecting gpy
  Downloading GPy-1.8.5.tar.gz (856kB)
    100% |████████████████████████████████| 860kB 1.3MB/s 
Collecting gpyopt
  Using cached GPyOpt-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/ahundt/pip-build-fcsazi50/gpyopt/setup.py", line 6, in <module>
        from GPyOpt.__version__ import __version__
      File "/tmp/ahundt/pip-build-fcsazi50/gpyopt/GPyOpt/__init__.py", line 7, in <module>
        from GPyOpt.core.task.space import Design_space
      File "/tmp/ahundt/pip-build-fcsazi50/gpyopt/GPyOpt/core/__init__.py", line 4, in <module>
        from .bo import BO
      File "/tmp/ahundt/pip-build-fcsazi50/gpyopt/GPyOpt/core/bo.py", line 9, in <module>
        from ..util.duplicate_manager import DuplicateManager
      File "/tmp/ahundt/pip-build-fcsazi50/gpyopt/GPyOpt/util/duplicate_manager.py", line 5, in <module>
        from ..core.task.space import Design_space
      File "/tmp/ahundt/pip-build-fcsazi50/gpyopt/GPyOpt/core/task/__init__.py", line 4, in <module>
        from .objective import SingleObjective
      File "/tmp/ahundt/pip-build-fcsazi50/gpyopt/GPyOpt/core/task/objective.py", line 8, in <module>
        import GPy
    ImportError: No module named 'GPy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/ahundt/pip-build-fcsazi50/gpyopt/

```

**Comment by ahundt** [comment]
It seems `gpy` might be different from `GPy`. I'm also not sure, my python is python2, is it possible for me to stick with that?

**Comment by ahundt** [comment]
Hmm another try, it seems I can import `tkinter` but not `_tkinter`:

```
± python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tkinter
>>> import _tkinter
>>> 
KeyboardInterrupt
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
ahundt@femur|~/src/costar_ws/src/costar_plan/costar_google_brainrobotdata on grasp_pixel_wise_training?
± pip2 install --user --upgrade GPy GPyOpt
Collecting GPy
  Using cached GPy-1.8.5.tar.gz
Collecting GPyOpt
  Using cached GPyOpt-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/ahundt/pip-build-t9ol8c/GPyOpt/setup.py", line 6, in <module>
        from GPyOpt.__version__ import __version__
      File "GPyOpt/__init__.py", line 7, in <module>
        from GPyOpt.core.task.space import Design_space
      File "GPyOpt/core/__init__.py", line 4, in <module>
        from .bo import BO
      File "GPyOpt/core/bo.py", line 9, in <module>
        from ..util.duplicate_manager import DuplicateManager
      File "GPyOpt/util/duplicate_manager.py", line 5, in <module>
        from ..core.task.space import Design_space
      File "GPyOpt/core/task/__init__.py", line 4, in <module>
        from .objective import SingleObjective
      File "GPyOpt/core/task/objective.py", line 8, in <module>
        import GPy
    ImportError: No module named GPy
    
    ----------------------------------------

```

**Comment by ahundt** [comment]
Figured out something that worked for me:
`pip2 install gpy gpyopt --user --upgrade`

**Comment by ahundt** [comment]
Apparently the trouble is with the python3 version:

```
± pip3 install gpy gpyopt --user --upgrade
Requirement already up-to-date: gpy in /home/ahundt/.local/lib/python3.5/site-packages
Collecting gpyopt
  Using cached GPyOpt-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
        import _tkinter
    ImportError: No module named '_tkinter'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/ahundt/pip-build-hmivpqc2/gpyopt/setup.py", line 6, in <module>
        from GPyOpt.__version__ import __version__
      File "/tmp/ahundt/pip-build-hmivpqc2/gpyopt/GPyOpt/__init__.py", line 7, in <module>
        from GPyOpt.core.task.space import Design_space
      File "/tmp/ahundt/pip-build-hmivpqc2/gpyopt/GPyOpt/core/__init__.py", line 4, in <module>
        from .bo import BO
      File "/tmp/ahundt/pip-build-hmivpqc2/gpyopt/GPyOpt/core/bo.py", line 9, in <module>
        from ..util.duplicate_manager import DuplicateManager
      File "/tmp/ahundt/pip-build-hmivpqc2/gpyopt/GPyOpt/util/duplicate_manager.py", line 5, in <module>
        from ..core.task.space import Design_space
      File "/tmp/ahundt/pip-build-hmivpqc2/gpyopt/GPyOpt/core/task/__init__.py", line 4, in <module>
        from .objective import SingleObjective
      File "/tmp/ahundt/pip-build-hmivpqc2/gpyopt/GPyOpt/core/task/objective.py", line 8, in <module>
        import GPy
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/__init__.py", line 15, in <module>
        from . import plotting
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/__init__.py", line 127, in <module>
        change_plotting_library(lib)
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/__init__.py", line 19, in change_plotting_library
        from .matplot_dep.plot_definitions import MatplotlibPlots
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/matplot_dep/__init__.py", line 20, in <module>
        from .util import align_subplot_array, align_subplots, fewerXticks, removeRightTicks, removeUpperTicks
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/matplot_dep/util.py", line 31, in <module>
        from matplotlib import pyplot as plt
      File "/home/ahundt/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 116, in <module>
        _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
      File "/home/ahundt/.local/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
        [backend_name], 0)
      File "/home/ahundt/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
        from six.moves import tkinter as Tk
      File "/home/ahundt/.local/lib/python3.5/site-packages/six.py", line 92, in __get__
        result = self._resolve()
      File "/home/ahundt/.local/lib/python3.5/site-packages/six.py", line 115, in _resolve
        return _import_module(self.mod)
      File "/home/ahundt/.local/lib/python3.5/site-packages/six.py", line 82, in _import_module
        __import__(name)
      File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
        raise ImportError(str(msg) + ', please install the python3-tk package')
    ImportError: No module named '_tkinter', please install the python3-tk package
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/ahundt/pip-build-hmivpqc2/gpyopt/
-> [1]
ahundt@femur|~/src/costar_ws/src/costar_plan/costar_google_brainrobotdata on grasp_pixel_wise_training?
± pip install gpy gpyopt --user --upgrade
Requirement already up-to-date: gpy in /home/ahundt/.local/lib/python3.5/site-packages
Collecting gpyopt
  Using cached GPyOpt-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
        import _tkinter
    ImportError: No module named '_tkinter'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/ahundt/pip-build-1gqxmrfz/gpyopt/setup.py", line 6, in <module>
        from GPyOpt.__version__ import __version__
      File "/tmp/ahundt/pip-build-1gqxmrfz/gpyopt/GPyOpt/__init__.py", line 7, in <module>
        from GPyOpt.core.task.space import Design_space
      File "/tmp/ahundt/pip-build-1gqxmrfz/gpyopt/GPyOpt/core/__init__.py", line 4, in <module>
        from .bo import BO
      File "/tmp/ahundt/pip-build-1gqxmrfz/gpyopt/GPyOpt/core/bo.py", line 9, in <module>
        from ..util.duplicate_manager import DuplicateManager
      File "/tmp/ahundt/pip-build-1gqxmrfz/gpyopt/GPyOpt/util/duplicate_manager.py", line 5, in <module>
        from ..core.task.space import Design_space
      File "/tmp/ahundt/pip-build-1gqxmrfz/gpyopt/GPyOpt/core/task/__init__.py", line 4, in <module>
        from .objective import SingleObjective
      File "/tmp/ahundt/pip-build-1gqxmrfz/gpyopt/GPyOpt/core/task/objective.py", line 8, in <module>
        import GPy
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/__init__.py", line 15, in <module>
        from . import plotting
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/__init__.py", line 127, in <module>
        change_plotting_library(lib)
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/__init__.py", line 19, in change_plotting_library
        from .matplot_dep.plot_definitions import MatplotlibPlots
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/matplot_dep/__init__.py", line 20, in <module>
        from .util import align_subplot_array, align_subplots, fewerXticks, removeRightTicks, removeUpperTicks
      File "/home/ahundt/.local/lib/python3.5/site-packages/GPy/plotting/matplot_dep/util.py", line 31, in <module>
        from matplotlib import pyplot as plt
      File "/home/ahundt/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 116, in <module>
        _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
      File "/home/ahundt/.local/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
        [backend_name], 0)
      File "/home/ahundt/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
        from six.moves import tkinter as Tk
      File "/home/ahundt/.local/lib/python3.5/site-packages/six.py", line 92, in __get__
        result = self._resolve()
      File "/home/ahundt/.local/lib/python3.5/site-packages/six.py", line 115, in _resolve
        return _import_module(self.mod)
      File "/home/ahundt/.local/lib/python3.5/site-packages/six.py", line 82, in _import_module
        __import__(name)
      File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
        raise ImportError(str(msg) + ', please install the python3-tk package')
    ImportError: No module named '_tkinter', please install the python3-tk package
    
    ----------------------------------------

```
I'm just going to use the python2 version for now and leave this closed

**Comment by ahundt** [comment]
I've also been able to reproduce these errors on OSX, so I believe this is a valid issue and I'm reopening it.

**Comment by apaleyes** [comment]
Looking around the internet, looks like this can be caused by matplotlib, which seems to rely on Tkinter as a dependency. Have you tried any solutions discussed here? https://stackoverflow.com/questions/44101690/python3-importerror-no-module-named-tkinter

**Comment by ahundt** [comment]
I worked around it and was able to install some other way, I don't recall what I did exactly, I was leaving this here in case you wanted to prevent it for future users. I've been using gpyopt for months now and I've been pretty happy with it!

**Comment by apaleyes** [comment]
Thanks for the feedback!

I don't believe this is a gpyopt related issue, as the link above suggests the problem might be in matplotlib installation. However we can now use this issue as a reference if someone else faces this problem, so it's good to have it around, thanks for cutting it.

**Comment by Paalon** [comment]
I encountered similar problem:
```
↪ pip install gpyopt
Collecting gpyopt
  Using cached GPyOpt-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/setup.py", line 6, in <module>
        from GPyOpt.__version__ import __version__
      File "/private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/GPyOpt/__init__.py", line 7, in <module>
        from GPyOpt.core.task.space import Design_space
      File "/private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/GPyOpt/core/__init__.py", line 4, in <module>
        from .bo import BO
      File "/private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/GPyOpt/core/bo.py", line 9, in <module>
        from ..util.duplicate_manager import DuplicateManager
      File "/private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/GPyOpt/util/duplicate_manager.py", line 5, in <module>
        from ..core.task.space import Design_space
      File "/private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/GPyOpt/core/task/__init__.py", line 4, in <module>
        from .objective import SingleObjective
      File "/private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/GPyOpt/core/task/objective.py", line 8, in <module>
        import GPy
    ModuleNotFoundError: No module named 'GPy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xw/f40tcc457klcppv72p5gjb4c0000gn/T/pip-build-73w82x34/gpyopt/
```
