### ISSUE TITLE
Bug running gpyopt.py on example config files

### ISSUE THREAD

**Issue by nweir127** [SheffieldML/GPyOpt#165]
Hi, gpyopt.py crashes immediately after cloning and testing on both brainin and camel examples. 
```
python gpyopt.py examples/branin/config.json
Traceback (most recent call last):
  File "gpyopt.py", line 20, in <module>
    bo = driver.run()
  File "GPyOpt/GPyOpt/interface/driver.py", line 106, in run
    obj_func = self._get_obj(space)
  File "GPyOpt/GPyOpt/interface/driver.py", line 32, in _get_obj
    return SingleObjective(obj_func, self.config['resources']['cores'], space=space, unfold_args=True)
TypeError: __init__() got an unexpected keyword argument 'unfold_args'
```

**Comment by derlin** [comment]
Same here. Any update on this issue ?
