### ISSUE TITLE
Parallel demo does not work in Python 3.7

### ISSUE THREAD

**Issue by Mi5ke** [SheffieldML/GPyOpt#181]
Hi,

Trying to use GPyOpt in parallel. My code (and the example code) fails when num_cores > 1, at least under Python 3.7 - currently unable to try other versions. Example code:

```python
import GPyOpt
from numpy.random import seed
seed(123)

objective_true  = GPyOpt.objective_examples.experiments2d.branin()                 # true function
objective_noisy = GPyOpt.objective_examples.experiments2d.branin(sd = 0.1)         # noisy version
bounds = objective_noisy.bounds

domain = [{'name': 'var_1', 'type': 'continuous', 'domain': bounds[0]}, ## use default bounds
          {'name': 'var_2', 'type': 'continuous', 'domain': bounds[1]}]

batch_size = 4
num_cores = 4

BO_demo_parallel = GPyOpt.methods.BayesianOptimization(f=objective_noisy.f,
                                            domain = domain,
                                            acquisition_type = 'EI',
                                            normalize_Y = True,
                                            initial_design_numdata = 10,
                                            evaluator_type = 'local_penalization',
                                            batch_size = batch_size,
                                            num_cores = num_cores,
                                            acquisition_jitter = 0)
```

Under python 3.7, this results in:

```
Error in parallel computation. Fall back to single process!
```

The process continues, but slowly. Is it only supporting Python 2.7 - I thought that it was ported last year? Any help appreciated.

Mike

**Comment by nmurad1** [comment]
I'm getting the exact same error for Python 3.6.5 for even the sample problem. Was there a solution found for this?

Thanks a lot!
Neha

**Comment by rumusan** [comment]
Running this under windows will get the error, because of the problem about multiprocessing.

**Comment by Mi5ke** [comment]
Do you mean this is a known undocumented problem, which has no fix, yet appears as an example in the documentation?

**Comment by rumusan** [comment]
I am not sure. I can run it on a linux system，I guess this problem is due to multiprocessing module.
https://stackoverflow.com/questions/20222534/python-multiprocessing-on-windows-if-name-main

**Comment by SanderLam** [comment]
I'm running on Python 3.7.3, and also get the error when I exactly follow this tutorial:
https://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_parallel_optimization.ipynb

Next to falling back on the single process, I also get the following error:

Error in parallel computation. Fall back to single process!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\firstname.lastname\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\firstname.lastname\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Is there any update on this issue?

Thanks!
