### ISSUE TITLE
How to use Grid design for discrete only domain?

### ISSUE THREAD

**Issue by urjitbhatia** [SheffieldML/GPyOpt#191]
I am a little confused about optimizing discrete only domains using Grids.
```
domain = [{'name': 'var_1', 'type': 'discrete', 'domain': np.linspace(
    start=2, stop=300, num=100)}]

# Grid design
### --- Grid design
space = GPyOpt.Design_space(domain)
data_init = 10

X = initial_design('grid',space,data_init)
plt.plot(X[:,0],X[:,1],'b.')
plt.title('Grid design')
```

fails because we have 0 `continuous` dimensions https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/experiment_design/grid_design.py#L22

```Traceback (most recent call last):
  File "gpyopt.py", line 32, in <module>
    X = initial_design('grid',space,data_init)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/experiment_design/__init__.py", line 20, in initial_design
    return design.get_samples(init_points_count)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/experiment_design/grid_design.py", line 32, in get_samples
    init_points_count = self._adjust_init_points_count(init_points_count)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/experiment_design/grid_design.py", line 23, in _adjust_init_points_count
    self.data_per_dimension = iroot(continuous_dims, init_points_count)
  File "/usr/local/lib/python3.6/site-packages/GPyOpt/experiment_design/grid_design.py", line 57, in iroot
    u = t // k
ZeroDivisionError: float divmod()
make: *** [optimize] Error 1
```

Can you point me to the right direction about optimizations on discrete only domains?

**Comment by apaleyes** [comment]
Grid design only works with continuous variables, so this fails because you have none of those. For discrete it falls back to random design, so this is probably what you should be using.

**Comment by apaleyes** [comment]
Resolving , please reopen if this did not answer your question
