### ISSUE TITLE
GPyOpt Singuarlity Image

### ISSUE THREAD

**Issue by MaryHadley** [SheffieldML/GPyOpt#325]
Hi,

I've read the various docs about how to install GPyOpt, and I've had some trouble with all the methods, even checking out the package from Github. Ultimately, I would like to make a singularity image that has GPyOpt that I can pass on to others in my collaboration -- do you have instructions for creating such an image?

Thank you,
Mary

**Comment by apaleyes** [comment]
Hi. Unfortunately I've never even heard of "singularity image". Can you please elaborate what's that?

Also, can you share the issues you had install GPyOpt? It's just a Python package, so normally `pip install gpyopt` should work fine. If you could post what you have tried and what specific errors you've encountered, we might be able to help.

**Comment by ekalosak** [comment]
Hey fellow Bruno - I'm guessing, from what I've read on singularity, you might be looking for something like a Dockerfile that contains GPyOpt. This is going to be the same process as building a docker image with the GPyOpt package installed. As Andrei writes, you could do something like
```
FROM python3.8
RUN pip install gypopt
COPY myscript.py /
ENTRYPOINT python myscript.py
```

**Comment by MaryHadley** [comment]
Thanks for your quick and kind replies.

The problem seems to be (when working on my mac, which only has python 2):

pip install GPyOpt
Collecting GPyOpt
Collecting scipy>=0.16 (from GPyOpt)
  Using cached
https://files.pythonhosted.org/packages/dc/7a/3de1700fb471a6f56353446b4b962a7e4a5baaf24e5e4dec2d91d5f500da/scipy-1.2.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: numpy>=1.7 in
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
(from GPyOpt)
Collecting GPy>=1.8 (from GPyOpt)
  Using cached
https://files.pythonhosted.org/packages/40/13/4112894b8ef87847b50a6d04acdab1366aafadf0a78e4207e65c33e82b8a/GPy-1.9.9-cp27-cp27m-macosx_10_7_x86_64.whl
Requirement already satisfied: six in
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
(from GPy>=1.8->GPyOpt)
Collecting paramz>=0.9.0 (from GPy>=1.8->GPyOpt)
Collecting decorator>=4.0.10 (from paramz>=0.9.0->GPy>=1.8->GPyOpt)
  Using cached
https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Installing collected packages: scipy, decorator, paramz, GPy, GPyOpt
  Found existing installation: scipy 0.13.0b1
    DEPRECATION: Uninstalling a distutils installed project (scipy) has
been deprecated and will be removed in a future version. This is due to the
fact that uninstalling a distutils project will only partially uninstall
the project.
    Uninstalling scipy-0.13.0b1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in
main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line
342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in
install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line
754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line
115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267,
in renames
    shutil.move(old, new)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py",
line 325, in move
    copy2(src, real_dst)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py",
line 154, in copy2
    copystat(src, dst)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py",
line 123, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted:
'/var/folders/f8/88v7l4yn5v577qwbhl_vbpgm0000gn/T/pip-UUQ8F5-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy-0.13.0b1-py2.7.egg-info'
You are using pip version 9.0.3, however version 20.1.1 is available.
*You should consider upgrading via the 'pip install --upgrade pip*' command.

So I try that:
pip install --upgrade pip


 pip install --upgrade pip
Collecting pip
  Using cached
https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in
main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line
342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in
install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line
754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line
115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267,
in renames
    shutil.move(old, new)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py",
line 326, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied:
'/Library/Python/2.7/site-packages/pip-9.0.3.dist-info/DESCRIPTION.rst'
You are using pip version 9.0.3, however version 20.1.1 is available.
*You should consider upgrading via the 'pip install --upgrade pip' command.*

So looks like I may have 3 problems -- the fact that this pip installation
of GPyOpt isn't working, the fact that pip install upgrade isn't working,
and the fact that I don't have python3.

I suppose, since my goal really is to make the docker image, that I could
just try the commands you suggested in a docker file. I am a docker very
newbie, so was trying to test things locally on my laptop first.
Thank you,
Mary

**Comment by apaleyes** [comment]
What I see in the installation log is just a permission issue, nothing to do with gpyopt or python version. By default pip installs packages into system directory, which requires root access. Things you could do:
* sudo pip install gpyopt
* pip install gpyopt --user
* Create a [virtual environment](https://docs.python-guide.org/dev/virtualenvs/)

**Comment by MaryHadley** [comment]
Thank you!

**Comment by ekalosak** [comment]
@MaryHadley when you figure this out, it would be great to have your Dockerfile (or a stripped down example) in the wiki: https://github.com/SheffieldML/GPyOpt/wiki
