### ISSUE TITLE
Error when choose other acquisition_optimizer_type

### ISSUE THREAD

**Issue by chinux23** [SheffieldML/GPyOpt#35]
``` python
In [6]:

myProblem = GPyOpt.methods.BayesianOptimization(
    CO, 
    bounds, 
    exact_feval=True,
    maximize = True,
    normalize_Y = True,
    num_cores = 7,
    batch_size = 7,
    acquisition_optimizer_type='DIRECT',
    evaluator_type = 'random'
)
Cannot find DIRECT library, please install it to use this option.
3.2091067970977254 28.0 125.0
2.3088033218144273 31.0 313.0
4.767196848416326 30.0 106.0
3.699853608735686 18.0 300.0
0.11330175343781992 19.0 115.0
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-e8c2660be0d5> in <module>()
      8     batch_size = 7,
      9     acquisition_optimizer_type='DIRECT',
---> 10     evaluator_type = 'random'
     11 )

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/methods/bayesian_optimization.py in __init__(self, f, domain, constrains, cost_withGradients, model_type, X, Y, initial_design_numdata, initial_design_type, acquisition_type, normalize_Y, exact_feval, acquisition_optimizer_type, model_update_interval, evaluator_type, batch_size, num_cores, verbosity, verbosity_model, bounds, maximize, **kwargs)
    241 
    242         # --- Initialize everything
--> 243         self.run_optimization(max_iter=0,verbosity=self.verbosity)
    244 
    245     def _model_chooser(self):

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/methods/bayesian_optimization.py in run_optimization(self, max_iter, max_time, eps, verbosity, save_models_parameters, report_file, evaluations_file, models_file, **kwargs)
    455                 self.acquisition_optimizer.optimizer ='CMA'
    456             print('WARNING: "acqu_optimize_method" will be deprecated in the next version!')
--> 457         super(BayesianOptimization, self).run_optimization(max_iter = max_iter, max_time = max_time,  eps = eps, verbosity=verbosity, save_models_parameters = save_models_parameters, report_file = report_file, evaluations_file= evaluations_file, models_file=models_file)
    458 
    459     def _sign(self,f):

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/core/bo.py in run_optimization(self, max_iter, max_time, eps, verbosity, save_models_parameters, report_file, evaluations_file, models_file)
    106 
    107             # --- Update and optimize acquisition and compute the exploration level in the next evaluation
--> 108             self.suggested_sample = self._compute_next_evaluations()
    109 
    110             if not ((self.num_acquisitions < self.max_iter) and (self._distance_last_evaluations() > self.eps)):

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/core/bo.py in _compute_next_evaluations(self)
    184         Computes the location of the new evaluation (optimizes the acquisition in the standard case).
    185         """
--> 186         return self.evaluator.compute_batch()
    187 
    188     def _update_model(self):

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/core/evaluators/batch_random.py in compute_batch(self)
     25         Adds to the first location batch_size-1 randomly selected elements.
     26         """
---> 27         return np.vstack((self.acquisition.optimize(),initial_design('random',self.acquisition.space,self.batch_size-1)))

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/acquisitions/base.py in optimize(self)
     57             out = self.optimizer.optimize(f=self.acquisition_function)[0]
     58         else:
---> 59             out = self.optimizer.optimize(f=self.acquisition_function, f_df=self.acquisition_function_withGradients)[0]
     60         return out
     61 

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/optimization/acquisition_optimizer.py in optimize(self, f, df, f_df)
    281         for i in range(num_discrete):
    282             self.mixed_optimizer.fix_dimensions(dims=self.discrete_dims, values=self.discrete_values[i,:])
--> 283             partial_x_min[i,:] , partial_f_min[i,:] = self.mixed_optimizer.optimize(f, df, f_df)
    284 
    285         return np.atleast_2d(partial_x_min[np.argmin(partial_f_min)]), np.atleast_2d(min(partial_f_min))

/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/optimization/acquisition_optimizer.py in optimize(self, f, df, f_df)
    175             if self.search:
    176                 if self.f_df == None: fp_dfp = None  # -- In case no gradients are available
--> 177                 x_min, f_min = self.optimizer.optimize(x0, f =fp, df=None, f_df=fp_dfp)
    178                 return self._expand_vector(x_min), f_min
    179             else:

TypeError: 'NoneType' object is not utterable
```

for "DIRECT", the actual exception is this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/optimization/optimizer.py", line 96, in optimize
    x,_,_ = solve(DIRECT_f_wrapper(f),lB,uB, maxT=self.maxiter)
  File "/usr/local/lib/python3.5/site-packages/DIRECT/__init__.py", line 206, in solve
    raise Exception(ERROR_MESSAGES[abs(ierror)-1])
IndexError: tuple index out of range
```

Similar error is observed when "CMA" is chosen.

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/GPyOpt-1.0.2-py3.5.egg/GPyOpt/optimization/optimizer.py", line 123, in __init__
    x = cma.fmin(CMA_f_wrapper(f), (uB + lB) * 0.5, 0.6, options={"bounds":[lB, uB], "verbose":-1})[0]
NameError: name 'f' is not defined
Traceback (most recent call last):
```

The exception is bit misleading, because the error is caused by 'f' not defined.

**Comment by javiergonzalezh** [comment]
You need to install the libraries DIRECT and cma. You can do it using pip.

**Comment by chinux23** [comment]
The exception is claiming that DIRECT and cma was not installed, which is misleading, because those are installed.

**Comment by tinutjoy** [comment]
Sometimes pip will not work for DIRECT. Try installing from https://pypi.python.org/pypi/DIRECT/ . This has worked for me.

**Comment by tinutjoy** [comment]
Interesting, cma is not working even though I have installed cma. Is cma wrapper functional?
