### ISSUE TITLE
Getting an error when running myBopt.plot_acquisition() from tutorial

### ISSUE THREAD

**Issue by Fauntman** [SheffieldML/GPyOpt#355]
Just  by running the tutorial on my notebook I get an error when it comes to run

`myBopt.plot_acquisition()
`

The error:

`Traceback (most recent call last):

  File "C:\Users\hp\Desktop\PHD\Projects\untitled3.py", line 33, in <module>
    myBopt.plot_acquisition()

  File "C:\Users\hp\anaconda3\lib\site-packages\GPyOpt\core\bo.py", line 284, in plot_acquisition
    return plot_acquisition(self.acquisition.space.get_bounds(),

  File "C:\Users\hp\anaconda3\lib\site-packages\GPyOpt\plotting\plots_bo.py", line 64, in plot_acquisition
    model.plot_density(bounds[0], alpha=.5)

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\gpy_plot\gp_plots.py", line 257, in plot_density
    plots = _plot_density(self, canvas, helper_data, helper_prediction, label, **kwargs)

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\gpy_plot\gp_plots.py", line 271, in _plot_density
    fills.append(pl().fill_gradient(

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\matplot_dep\plot_definitions.py", line 244, in fill_gradient
    ax._process_unit_info(xdata=X, ydata=y1)

TypeError: _process_unit_info() got an unexpected keyword argument 'xdata'

runcell(0, 'C:/Users/hp/Desktop/PHD/Projects/untitled3.py')
Traceback (most recent call last):

  File "C:\Users\hp\Desktop\PHD\Projects\untitled3.py", line 33, in <module>
    myBopt.plot_acquisition()

  File "C:\Users\hp\anaconda3\lib\site-packages\GPyOpt\core\bo.py", line 284, in plot_acquisition
    return plot_acquisition(self.acquisition.space.get_bounds(),

  File "C:\Users\hp\anaconda3\lib\site-packages\GPyOpt\plotting\plots_bo.py", line 64, in plot_acquisition
    model.plot_density(bounds[0], alpha=.5)

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\gpy_plot\gp_plots.py", line 257, in plot_density
    plots = _plot_density(self, canvas, helper_data, helper_prediction, label, **kwargs)

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\gpy_plot\gp_plots.py", line 271, in _plot_density
    fills.append(pl().fill_gradient(

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\matplot_dep\plot_definitions.py", line 244, in fill_gradient
    ax._process_unit_info(xdata=X, ydata=y1)

TypeError: _process_unit_info() got an unexpected keyword argument 'xdata'

runcell(0, 'C:/Users/hp/Desktop/PHD/Projects/untitled3.py')
Traceback (most recent call last):

  File "C:\Users\hp\Desktop\PHD\Projects\untitled3.py", line 33, in <module>
    myBopt.plot_acquisition()

  File "C:\Users\hp\anaconda3\lib\site-packages\GPyOpt\core\bo.py", line 284, in plot_acquisition
    return plot_acquisition(self.acquisition.space.get_bounds(),

  File "C:\Users\hp\anaconda3\lib\site-packages\GPyOpt\plotting\plots_bo.py", line 64, in plot_acquisition
    model.plot_density(bounds[0], alpha=.5)

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\gpy_plot\gp_plots.py", line 257, in plot_density
    plots = _plot_density(self, canvas, helper_data, helper_prediction, label, **kwargs)

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\gpy_plot\gp_plots.py", line 271, in _plot_density
    fills.append(pl().fill_gradient(

  File "C:\Users\hp\anaconda3\lib\site-packages\GPy\plotting\matplot_dep\plot_definitions.py", line 244, in fill_gradient
    ax._process_unit_info(xdata=X, ydata=y1)

TypeError: _process_unit_info() got an unexpected keyword argument 'xdata`

**Comment by wak-shogo** [comment]
I had a same error, and successfully fixed as follows.
This problem would be caused by the change of matplotlib function `_process_unit_info()`. 
For me, downgrading matplotlib to 3.1.3 ( `pip install matplotlib==3.1.3`) works.

**Comment by Sherif-elsoudy** [comment]
Help us please, the same error here

**Comment by Sherif-elsoudy** [comment]
help please
